function insert_line(handles, user_cent, video, frameNo, i)%сединим желтыми линиями маркеры  
axes(handles.axes1);
frame = read(video,frameNo);
for p = 1:4 
    frame = insertShape(frame,'line',[user_cent(i,p).Centroid(1)...
                                              user_cent(i,p).Centroid(2)...
                                              user_cent(i,p+1).Centroid(1)...
                                              user_cent(i,p+1).Centroid(2)],...
                                              'LineWidth',5, 'color','blue');
    image(frame);
end